# Generated by Django 2.2 on 2020-12-23 11:31

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, help_text='Enter the first name', max_length=50, null=True, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, help_text='Enter the last name', max_length=50, null=True, verbose_name='Last name')),
                ('language', models.CharField(choices=[('fr', 'French'), ('en', 'English')], default='fr', help_text='Choose your preferred language', max_length=50, verbose_name='Language')),
                ('phone', models.CharField(blank=True, help_text='Enter the phone number', max_length=50, null=True, unique=True, verbose_name='Phone number')),
                ('country', models.CharField(choices=[('Chile', 'Chile'), ('Brazil', 'Brazil'), ('Canada', 'Canada'), ('Peru', 'Peru'), ('Mexico', 'Mexico'), ('US', 'United states')], default='Chile', help_text='Choose the country of the employee', max_length=255, verbose_name='Country')),
                ('is_active', models.BooleanField(default=False)),
                ('is_responsible', models.BooleanField(default=False)),
                ('is_employee', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_meal', models.CharField(help_text='Enter the name of the principal meal', max_length=255, verbose_name='the principal meal')),
                ('salad', models.CharField(help_text='Enter the name of the salad', max_length=255, verbose_name='salad')),
                ('dessert', models.CharField(help_text='Enter the name of the dessert', max_length=255, verbose_name='dessert')),
            ],
        ),
        migrations.CreateModel(
            name='Responsible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlannedMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_date', models.DateField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('meals', models.ManyToManyField(to='lunchapp.Meal')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default='23532985-9dbc-4a65-8752-fda44ab1e85d', editable=False, max_length=50, verbose_name='UUID Employee')),
                ('preferred_meal', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='lunchapp.Meal')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
