# Generated by Django 2.2 on 2020-12-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunchapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='customizations',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Employee customizations'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='uuid',
            field=models.CharField(default='77d035f5-6223-4724-91ca-26c225239e6e', editable=False, max_length=50, verbose_name='UUID Employee'),
        ),
    ]
