# Generated by Django 2.2 on 2020-12-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunchapp', '0002_auto_20201223_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='uuid',
        ),
        migrations.AddField(
            model_name='plannedmenu',
            name='uuid_menu',
            field=models.CharField(default='2d47388c-75af-48aa-a4ce-64cae51f6f60', editable=False, max_length=50, verbose_name='UUID Menu'),
        ),
    ]
