# Generated by Django 2.2 on 2020-12-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunchapp', '0003_auto_20201223_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plannedmenu',
            name='uuid_menu',
            field=models.CharField(default='0eab7e68-e6d5-4aa8-a796-6d84e712da52', editable=False, max_length=50, unique=True, verbose_name='UUID Menu'),
        ),
    ]
